name: Daily Swiss Tournament

on:
  workflow_dispatch:   # erlaubt manuelles Starten
  schedule:
    - cron: "0 14 * * *"   # Täglich 14:00 UTC = 16:00 Deutschland (Sommerzeit)

jobs:
  swiss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Swiss Maker
        run: OAUTH_TOKEN=${{ secrets.LICHESS_TOKEN }} yarn dev
